name: Build and publish

on:
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build wheel and sdist
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      package_version: ${{ steps.baipp.outputs.package_version }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: hynek/build-and-inspect-python-package@d44ca7d91762de7a7d5436ddae667c6da6d1c3df # v2.18.0
      id: baipp

  publish:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/project/tap-tursoapi/${{ needs.build.outputs.package_version }}
    permissions:
      contents: write # Upload artifacts to release
      id-token: write # Required by pypa/gh-action-pypi-publish for trusted publishing

    steps:
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: Packages
        path: dist
    - uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1
